defmodule LinearCloneWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :linear_clone

  # Allowed CORS origins. Exact strings only - no regex, since plug macro
  # arg escaping does not handle compiled Regex references. Add new Vercel
  # preview URLs to this list as needed.
  @cors_origins [
    "http://localhost:3000",
    "https://linear-clone-inky.vercel.app",
    "https://linear-clone-git-main-himanshu-7687s-projects.vercel.app",
    "https://linear-clone-himanshu-7687s-projects.vercel.app"
  ]

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_linear_clone_key",
    signing_salt: "biec0gzu",
    same_site: "Lax"
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :linear_clone,
    gzip: not code_reloading?,
    only: LinearCloneWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :linear_clone
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Corsica,
    origins: @cors_origins,
    allow_headers: ["content-type", "authorization"],
    allow_methods: ["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"]

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug LinearCloneWeb.Router
end
